name: AuroraKits
version: '${version}'
main: club.aurorapvp.AuroraKits
api-version: 1.19
authors: [ Villagers654 ]
description: A Crystal PvP Kits Plugin for the Aurora Network
website: aurorapvp.club
commands:
  aurorakits:
    subcommands: reload
  kit:
    description: Opens a kit
    usage: /kit [name]
  kits:
    description: Opens the Kit GUI
    usage: /kits
  createkit:
    description: Creates a kit
    usage: /createkit [name]
  deletekit:
    description: Deletes a kit
    usage: /deletekit [name]
  createpublickit:
    description: Creates a Public Kit
    usage: /createpublickit [name]
  deletepublickit:
    description: Deletes a Public Kit
    usage: /deletepublickit [name]
  createframe:
    description: Creates an item frame which can dispense items
    usage: /createframe [name]
  deleteframe:
    description: Deletes a an item frame
    usage: /deleteframe [name]
permissions:
  AuroraKits.kit:
    description: Receive alerts for violations
    default: true
  AuroraKits.deletekit:
    description: Receive alerts for violations
    default: true
  AuroraKits.createkit:
    description: Receive alerts for violations
    default: true
  AuroraKits.public:
    description: Show client brands on join
    default: op
  AuorraKits.frames:
    description: Send cheater alert
    default: op